name: pattern_recognition_env
python: 3.6
channels:
dependencies:
   - pip:
       - "--editable=git+https://github.com/olemb/mido"
   - scipy=1.0.1
   - Keras=2.1.5
   - tensorflow
   - scikit-image=0.13.1
   - matplotlib=2.1.2
   - jupyter=1.0.0
   - pandas=0.22.0

   - Cython==0.28.2
   - mypy
   - pydot
   - graphviz
