name: pattern_recognition
channels:
dependencies:
   - scipy=1.0.1
   - Keras=2.1.5
   - tensorflow
   - scikit-image=0.13.1
   - matplotlib=2.1.2
   - jupyter=1.0.0
   - pandas=0.22.0

   - Cython==0.28.2
   - mypy
   - pydot
   - graphviz
