site_name: Pattern Recognition Docs
# theme: readthedocs
repo_url: http://github.com/voschezang/pattern-recognition
site_url: https://voschezang.github.io/pattern-recognition/
site_description: 'Documentation for pattern-generation.'

dev_addr: '0.0.0.0:8000'

pages:
- Home: index.md
- About: about.md
- About-copy: about.md
